[package]
name = "aeadify"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = [ "derive" ] }
orion = "0.17.6"
base64 = "0.22.0"
sled = "0.34.7"
bincode = "1.3.3"